language: python

cache: pip

dist: trusty

python:
  - "2.7"
  - "3.6"

before_install:
  - pip install -U pip
  - ./travis_setup.py

install:
  - pip install coveralls
  - pip install -e .  

script:
  - python setup.py test
  - coverage run --source=geextract/ setup.py test

after_success:
  - coveralls

warnings_are_errors: true

notifications:
  email: false
