language: python

cache: pip

dist: trusty

python:
  - "2.7"
  - "3.6"

before_install:
  - pip install -U pip
  - ./travis_setup.py

install:
  - pip install -e .  

script:
  - python setup.py test

warnings_are_errors: true

notifications:
  email: false
